### ISSUE TITLE
template props

### ISSUE THREAD

**Issue by prosperva** [arcnovus/wet-boew-x#33]
Is there a specific prop to pass to DefaultTemplate to achieve this template where some sections extend out: https://www.nrcan.gc.ca/home. One of the extended out section is the **Featured** section. 

I was able to find the class that allows this: **gc-instttn** but wondering how it gets passed.

Thanks

**Comment by arcdev1** [comment]
😞 Turns out this is difficult because of a bug (#34). 

I will add the fix to v2. In the meantime...

The workaround is to create your own custom template that uses a regular `<main>` tag. The code is below, BUT it means that you will need to wrap any **non-full-width** content with a `<Container>`.

## Custom Template Component
```tsx
/* eslint-disable react/no-unknown-property */
import { PropsWithChildren } from "react";
import {
  RefTopProps,
  TopProps,
  PreFooterProps,
  FooterProps,
  RefFooterProps,
  RefTop,
  Top,
  PreFooter,
  Footer,
  RefFooter,
  AfterCdts,
  useLngLinks,
  Container,
} from "@arcnovus/wet-boew-react";

export type CustomTemplateProps = PropsWithChildren<
  Omit<RefTopProps, "isApplication"> &
    TopProps &
    PreFooterProps &
    FooterProps &
    RefFooterProps
>;

export default function CustomTemplate({
  children,
  lngLinks,
  ...props
}: CustomTemplateProps) {
  const languageToggle = useLngLinks({ lngLinks });
  return (
    <>
      <RefTop {...props} isApplication={false} />
      <Top {...props} lngLinks={languageToggle.lngLinks} />
      <main
        property="mainContentOfPage"
        resource="#wb-main"
        typeof="WebPageElement"
        {...props}
      >
        <AfterCdts>{children}</AfterCdts>
        <Container>
          <PreFooter {...props} />
        </Container>
      </main>
      <Footer {...props} />
      <RefFooter {...props} isApplication={false} />
    </>
  );
}
```

## Page with Full Width Content
```tsx
import { Container, DefaultTemplate, Row } from "@arcnovus/wet-boew-react";
import CustomTemplate from "../../components/CustomTemplate";

export default function FeaturedAndMostRequested() {
  return (
    <CustomTemplate>
      <Container>
        <h1>Featured and Most Requested</h1>
      </Container>
      <div
        className="opct-90"
        style={{
          marginBottom: "0em",
          paddingTop: "20px",
          paddingBottom: "20px",
          background: "#31708f",
        }}
      >
        <Container>
          <Row>
            <div className="mrgn-tp-md mrgn-bttm-md col-xs-12">
              <p className="pull-left mrgn-bttm-0 text-white mrgn-rght-sm">
                Featured:
              </p>
              <p className="pull-left mrgn-bttm-0">
                <a
                  className="stretched-link text-white"
                  href="https://www.nrcan.gc.ca/simply-science/hope-climate-change-canadas-arctic-ocean/22831"
                >
                  Simply Science - Hope for Climate Change From Canadas Arctic
                  Ocean
                </a>
              </p>
            </div>
          </Row>
        </Container>
      </div>
      <Container>Constrained content here</Container>
      <div
        className="most-requested well well-sm brdr-0"
      >
        <Container>Full width content here.</Container>
      </div>
    </CustomTemplate>
  );
}

```

**Comment by arcdev1** [comment]
> Thanks for this @arcdev1. I will try it out.

Feel free to come back if there are any issues and I will re-open with additional support 😄

**Comment by prosperva** [comment]
I think my next one is the tabs which I saw you created an issue for.

It is one component we are looking for.

**Comment by arcdev1** [comment]
> I think my next one is the tabs which I saw you created an issue for. It is one component we are looking for.

Tabs will be in the full release of v2 for sure. But keep in mind that you have access to all the WET CSS as long as your app is wrapped in the `<WetProvider>` so if you ever need a component that hasn't been built yet, you can just follow the examples in the [wet style guide](https://wet-boew.github.io/wet-boew-styleguide/index-en.html) and replace `class=...` with `className=...` 

So, something like this would probably work (not tested).

```html
<div className="wb-tabs">
  <div className="tabpanels">
    <details id="details-panel1">
      <summary>Example 1</summary>
        <p>
          ...
        </p>
      </details>
      <details id="details-panel2" open="open">
        <summary>Example 2</summary>
        <p>
          ...
        </p>
     </details>
        ...
  </div>
</div>
```

**Comment by prosperva** [comment]
Hi @arcdev1 

I am running into this issue:

`Compiled with problems:X

ERROR in ./node_modules/@arcnovus/wet-boew-react/src/cdts/AfterCdts.tsx 4:38

Module parse failed: Unexpected token (4:38)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| import { useCdts } from "./useCdts";
| 
> export function AfterCdts({ children }: PropsWithChildren<any>) {
|   const { wetBuilder } = useCdts() ?? {};
|   return <>{wetBuilder && children}</>;`

**Comment by arcdev1** [comment]
Hmmm ... what version of @arcnovus/wet-boew-react are you using? I believe 2.0.0-beta.0 has this exported.

**Comment by prosperva** [comment]
I updated to 2.0.0-beta.0 and it worked. Thanks

**Comment by prosperva** [comment]
<img width="2285" alt="Screen Shot 2022-10-19 at 12 57 37 PM" src="https://user-images.githubusercontent.com/1531271/196780146-bfa4509d-5adf-4820-966d-022d5fee36b6.png">

**Comment by prosperva** [comment]
The government of Canada banner and the PreFooter are not playing nice. I tried moving them in the main but it does not work.

**Comment by prosperva** [comment]
Makes sense not to change them. Our designer gave us this site (https://atlas.gc.ca/critical-minerals/en/index.html) as an example

**Comment by prosperva** [comment]
Thanks for your suggestions. I will pass them to the designer.

**Comment by prosperva** [comment]
Is there a way to disable/remove search?

**Comment by arcdev1** [comment]
> Is there a way to disable/remove search?

Yes. Pass "search={false}" `<DefaultTemplate search={flase}>`
