### ISSUE TITLE
CDTS Template Change

### ISSUE THREAD

**Issue by ianwilk20** [arcnovus/wet-boew-x#42]
I am using the _@arcnovus/wet-boew-react_ 1.0.15-alpha.4 package. It appears like regardless of the _@arcnovus/wet-boew-react_ package version I use, it automatically retrieves the latest version of CDTS gcweb scripts v4_0_47 ([link 1](https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_47/wet-boew/js/wet-boew.min.js), [link 2](https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_47/wet-boew/js/theme.min.js), [link 3](https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_47/cdts/cdtscustom.js)). As a result of the _@arcnovus/wet-boew-react_  package pulling the most recent CDTS scrips, the CDTS footer has significantly changed in design. For some reason the Contact information link is in a separate div (.gc-contextual) from the Terms and conditions and Privacy links (.gc-sub-footer), and has a dark blue background:

![image](https://user-images.githubusercontent.com/47506745/235705350-e4e27971-3a04-40fb-8754-769b5bd09c70.png)

Is there any way to choose which version of the CDTS gcweb scripts we use so we can have the old footer back (v4_0_43)? Or is there an easier way to revert the footer back to the original on my end? For reference, this is what the footer looked like before:

![image](https://user-images.githubusercontent.com/47506745/235708858-a9b8a3ef-308f-4163-a962-74768f4ffc5b.png)

**Comment by arcdev1** [comment]
In theory you can pass a version prop to the WetProvider like:

```tsx
<WetProvider version="v4_0_43">
  <App />
</WetProvider>
```


The version prop accepts values that conform to the type:

```ts
export type CdtsVersion =
  | "run"
  | "rn"
  | `4.${number}.${number}`
  | `v4_${number}_${number}`;
 ```

https://github.com/arcnovus/wet-boew-x/blob/8d2c1a5b3f90f1be548fd65460638a188eff0d00/packages/wet-boew-utils/src/cdts-injector.ts#L261

In practice CDTS only keeps a few versions around and this feature is not super well tested. I am happy to help debug any issues you discover to the extent that they are not caused by the underlying CDTS service itself. Just create a new issue and we can work it together :)

Worst case scenario; you can build your own footer like what is discribed at issue #3

**Comment by ianwilk20** [comment]
Hello @arcdev1,

Thank you for explaining and providing me with some options. If I'm understanding correctly, passing the version to the WetProvider component could cause problems down the line with it a) not being well tested and b) CDTS only keeping a few prior versions around. You also suggested I could build my own footer. It seems like passing the version is a bit risky, so building my own footer is the best long-term route. 

Just to be certain, have I understood correctly what you've said and are those only two options that are available at this time?

**Comment by arcdev1** [comment]
Hi @ianwilk20 .... sorry for not being more clear. My advice is to always strive to be on the latest version of CDTS, this will best keep you in compliance with GC standards and policies. 

The version prop is there to give projects time to adapt to any changes in CDTS, especially if CDTS introduces a "breaking" change to their application. The idea is to pin to an earlier version *temporarily* while the project adapts itself to the latest version. 

If you do this then the fact that CDTS only keeps a few previous versions around shouldn't be a problem and you benefit from having CDTS take care of compliance for you (which is their whole value proposition).

If you have an absolute requirement to deviate from the templates provided by CDTS and you've passed through governance and gotten all the requisite approvals then you can take matters into your own hands and build a custom footer, but now you own it and need to maintain it. To me, this would be a last resort.

**Comment by ianwilk20** [comment]
Hey @arcdev1,

That definitely clarifies it for me, in that CDTS is always in alignment with the GC standards and policies and that's why it's beneficial to keep up to date with their latest version, unless, as you mentioned, there's some kind of breaking change.

The reason I brought up deviating from the footer template provided by CDTS is that I was informed by the UI/UX designer on my ISED internal-facing application that we should be placing our Contact link (which maps to the contactLink prop in your AppTemplate component) in the sub-footer beside the privacyLink and termsLink. As you are saying, though, CDTS has chosen the location of the contactLink (to now be in a separate blue contextual band) and by moving the link beside the privacyLink and termsLink, that would be a customization. If we wanted to do a customization, like you said that would require permission to do so (from my department, TBS or Principal Publisher)

**Comment by arcdev1** [comment]
@ianwilk20 

Yep!

Your UI/UX folks should be encouraged to follow the Government of Canada's [Technical specifications for the Web and mobile presence](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program/technical-specifications/web-mobile-presence.html)

Any deviation from this likely requires some form of governance approval.
