### ISSUE TITLE
DataTable component - Accessibility issue

### ISSUE THREAD

**Issue by ianwilk20** [arcnovus/wet-boew-x#45]
My project is using: @arcnovus/wet-boew-react: 2.0.0-beta.9 
React version: 17.0.2

I have added the [DataTable component](https://github.com/arcnovus/wet-boew-x/blob/main/packages/wet-boew-react/src/tables/DataTable.tsx) to a page in my project. 

When you add a table with more than 10 rows, the pagination kicks in. Run axe DevTools, you'll get this accessibility issue marked as critical:

![image](https://github.com/arcnovus/wet-boew-x/assets/47506745/f7eb83b8-b0e3-4d41-8ec5-6e934d68589e)

It says that to solve this problem, you need to fix the following:
_ARIA attribute is not allowed: aria-pressed="true"_

It looks like the pagination buttons use `<a>` tags to go between pages. I assume because the aria-pressed attribute is on an `<a>` tag axe DevTools is saying this is an accessibility issue, as aria-pressed should only be used on a button.

I tried applying the setting called [pagingTag](https://datatables.net/reference/option/pagingTag) to the DataTable, but that property is not available in the version you are using.  Would it be possible to update to DataTables 1.13.2 or to apply [this fix](https://datatables.net/forums/discussion/comment/216549/#Comment_216549) noted in the forums?

Thanks a bunch!

**Comment by arcdev1** [comment]
The datatable version is controlled by WET, so you would need to submit a PR over there.

File/Line to be changed:
https://github.com/wet-boew/wet-boew/blob/f73b3c7da2e78d5785e851469f869d6e331126b2/package.json#L44 

How to Contribute to WET:
https://github.com/wet-boew/wet-boew/blob/master/CONTRIBUTING.md

**Comment by ianwilk20** [comment]
@arcdev1, thank you for those resources. I'll try to get this change approved in the WET repo
